#!/usr/bin/env python3
import argparse
import json
import os
import smtplib
import ssl
from email.message import EmailMessage
from pathlib import Path


def env(name: str, required: bool = True, default: str | None = None) -> str | None:
    value = os.getenv(name, default)
    if required and not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def send_email(subject: str, body: str, to_email: str | None = None) -> None:
    dry_run = os.getenv("NOTIFICATION_DRY_RUN", "false").lower() == "true"

    smtp_host = env("SMTP_HOST", required=not dry_run)
    smtp_port = int(env("SMTP_PORT", required=not dry_run, default="587") or "587")
    smtp_username = env("SMTP_USERNAME", required=not dry_run)
    smtp_password = env("SMTP_PASSWORD", required=not dry_run)
    smtp_from = env("SMTP_FROM", required=not dry_run)
    recipient = to_email or env("MANAGER_EMAIL", required=not dry_run)

    if dry_run:
        print("NOTIFICATION_DRY_RUN=true; email not sent.")
        print(f"To: {recipient}")
        print(f"Subject: {subject}")
        print(body)
        return

    message = EmailMessage()
    message["From"] = smtp_from
    message["To"] = recipient
    message["Subject"] = subject
    message.set_content(body)

    context = ssl.create_default_context()

    with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
        server.starttls(context=context)
        server.login(smtp_username, smtp_password)
        server.send_message(message)


def build_initial_push(payload: dict) -> tuple[str, str]:
    subject = f"[Approval Required] PR #{payload['pr_number']}: {payload['title']}"
    body = f"""Hello,

A new pull request requires your review.

Repository: {payload['repository']}
Branch: {payload['branch']}
Pull Request: {payload['pr_url']}
Author: {payload['author']}
Commit SHA: {payload['sha']}

Approval SLA: 2 hours from PR creation.
Reminder cadence: every 15 minutes until approved or timed out.

Please review and approve if the change is acceptable.

This notification was generated by GitHub Actions.
"""
    return subject, body


def build_reminder(payload: dict) -> tuple[str, str]:
    prs = payload.get("pull_requests", [])
    subject = f"[Reminder] {len(prs)} PR(s) waiting for manager approval"

    lines = [
        "Hello,",
        "",
        "The following pull request(s) are still waiting for manager approval:",
        "",
    ]

    for pr in prs:
        lines.extend(
            [
                f"- PR #{pr['number']}: {pr['title']}",
                f"  URL: {pr['url']}",
                f"  Author: {pr['author']}",
                f"  Age minutes: {pr['age_minutes']}",
                f"  SLA status: {pr['sla_status']}",
                "",
            ]
        )

    lines.extend(
        [
            "Reminder cadence: every 15 minutes.",
            "Approval SLA: 2 hours from PR creation.",
            "",
            "This notification was generated by GitHub Actions.",
        ]
    )
    return subject, "\n".join(lines)


def build_approved(payload: dict) -> tuple[str, str]:
    subject = f"[Approved] PR #{payload['pr_number']}: {payload['title']}"
    body = f"""Hello,

The manager approval gate has been satisfied.

Repository: {payload['repository']}
Pull Request: {payload['pr_url']}
Approved By: {payload['approved_by']}

The workflow has attempted to enable auto-merge. If repository auto-merge is disabled, merge manually after required checks pass.

This notification was generated by GitHub Actions.
"""
    return subject, body


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--template", required=True, choices=["initial-push", "reminder", "approved"])
    parser.add_argument("--payload-file", required=True)
    args = parser.parse_args()

    payload = json.loads(Path(args.payload_file).read_text())

    if args.template == "initial-push":
        subject, body = build_initial_push(payload)
    elif args.template == "reminder":
        subject, body = build_reminder(payload)
    else:
        subject, body = build_approved(payload)

    send_email(subject, body)


if __name__ == "__main__":
    main()
